### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by szabozoltan69** [toggle-corp/re-map#41]
For https://github.com/toggle-corp/re-map/blob/develop/src/MapContainer/index.tsx#L23 some browsers give a "ResizeObserver loop limit exceeded" uncaught exception.
It also can be seen in GO Sentry: .../organizations/ifrc-go/issues/7.
@tnagorra

**Comment by tnagorra** [comment]
The resize observer polyfill has been removed from re-map.
We can now define resize observer polyfill on the application.
